apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespace.yaml
 - app-services/
 - frontend-ingress.yaml

patches:
 - patch: |-
     - op: replace
       path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
       value: 5
     - op: replace
       path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
       value: 5
   target:
     kind: Deployment
     labelSelector: "type=app-service"
